available_modules:
    pear:
        Authentication:
            - Auth_SASL2
            - OpenID
        Configuration:
            - Config_Lite
        Console:
            - Console_Color2
            - Console_CommandLine
            - Console_GetoptPlus
        Database:
            - DB_DataObject
            - DB_Sqlite_Tools
            - MDB2
            - MDB2_Driver_fbsql
            - MDB2_Driver_ibase
            - MDB2_Driver_mssql
            - MDB2_Driver_mysql
            - MDB2_Driver_mysqli
            - MDB2_Driver_oci8
            - MDB2_Driver_odbc
            - MDB2_Driver_pgsql
            - MDB2_Driver_querysim
            - MDB2_Driver_sqlite
            - MDB2_Driver_sqlsrv
            - SQL_Parser
        Date and Time:
            - Calendar
            - Date_Holidays
            - Date_Holidays_Austria
            - Date_Holidays_Netherlands
            - Date_HumanDiff
        Encryption:
            - Crypt_CHAP
            - Crypt_DiffieHellman
            - Crypt_GPG
            - Crypt_HMAC2
            - Crypt_MicroID
            - Crypt_RC42
        Event:
            - Event_SignalEmitter
        File Formats:
            - File_Bittorrent2
            - File_Cabinet
            - File_CSV_DataSource
            - File_DeliciousLibrary
            - File_Fortune
            - File_IMC
            - File_Infopath
            - File_MARC
            - File_Ogg
            - File_Sitemap
            - File_XSPF
            - MP3_IDv2
            - MP3_Playlist
            - OpenDocument
        File System:
            - File_Mogile
        Gtk2 Components:
            - Gtk2_EntryDialog
            - Gtk2_ExceptionDump
            - Gtk2_FileDrop
            - Gtk2_IndexedComboBox
            - Gtk2_PHPConfig
            - Gtk2_ScrollingLabel
            - Gtk2_VarDump
        HTML:
            - HTML_BBCodeParser2
            - HTML_Common2
            - HTML_Entities
            - HTML_QuickForm2
            - HTML_Safe
            - HTML_TagCloud
        HTTP:
            - HTTP2
            - HTTP_FloodControl
            - HTTP_Header2
            - HTTP_OAuth
            - HTTP_Request2
            - HTTP_Session2
        Images:
            - Image_3D
            - Image_Barcode2
            - Image_Color2
            - Image_Graph
            - Image_JpegMarkerReader
            - Image_JpegXmpReader
            - Image_QRCode
            - Image_Transform
        Internationalization:
            - I18N_UnicodeNormalizer
            - I18N_UnicodeString
        Logging:
            - Log
        Math:
            - Math_Combinatorics
        Networking:
            - Net_CheckIP2
            - Net_DNS2
            - Net_DNSBL
            - Net_GameServerQuery
            - Net_Gearman
            - Net_GeoIP
            - Net_Growl
            - Net_IDNA2
            - Net_LDAP2
            - Net_MAC
            - Net_MPD
            - Net_Nmap
            - Net_NNTP
            - Net_URL2
            - Net_URL_Mapper
            - Net_UserAgent_Mobile_GPS
            - Net_Vpopmaild
            - Net_WebFinger
            - URI_Template
        Payment:
            - Payment_DTA
            - Payment_PagamentoCerto
            - Payment_PayPal_SOAP
            - Payment_Process2
        PEAR:
            - PEAR_Command_Packaging
            - PEAR_Frontend_Gtk2
            - PEAR_PackageFileManager_Cli
            - PEAR_PackageFileManager_Frontend
            - PEAR_PackageUpdate_Gtk2
            - PEAR_RemoteInstaller
            - PEAR_Size
        PHP:
            - PHP_Archive
            - PHP_ArrayOf
            - PHP_Beautifier
            - PHP_CodeSniffer
            - PHP_Debug
            - PHP_DocBlockGenerator
            - PHP_FunctionCallTracer
            - PHP_LexerGenerator
            - PHP_Parser
            - PHP_ParserGenerator
            - PHP_Parser_DocblockParser
            - PHP_Shell
            - PHP_UML
        Semantic Web:
            - XML_GRDDL
        Structures:
            - OLE
            - Structures_DataGrid
            - Structures_DataGrid_DataSource_Excel
            - Structures_DataGrid_DataSource_PDO
            - Structures_Form
            - Structures_Form_Gtk2
            - Structures_LinkedList
        System:
            - System_Daemon
            - System_Launcher
        Text:
            - Text_CAPTCHA_Numeral
            - Text_Huffman
            - Text_LanguageDetect
        Testing:
            - Testing_DocTest
            - Testing_FIT
            - Testing_Selenium
        Tools and Utilities:
            - CodeGen
            - CodeGen_MySQL
            - CodeGen_MySQL_Plugin
            - CodeGen_MySQL_UDF
            - CodeGen_PECL
            - ScriptReorganizer
            - Search_Mnogosearch
        Validate:
            - Validate_ES
            - Validate_IR
            - Validate_LI
            - Validate_LU
            - Validate_NO
            - Validate_SE
        Version Control:
            - VersionControl_Git
            - VersionControl_SVN
        Web Services:
            - Services_Akismet2
            - Services_Amazon_S3
            - Services_Amazon_SQS
            - Services_Apns
            - Services_Atlassian_Crowd
            - Services_Blogging
            - Services_Compete
            - Services_Digg2
            - Services_ExchangeRates
            - Services_Facebook
            - Services_GeoNames
            - Services_Google
            - Services_Libravatar
            - Services_Mailman
            - Services_oEmbed
            - Services_OpenSearch
            - Services_OpenStreetMap
            - Services_PageRank
            - Services_ProjectHoneyPot
            - Services_ReCaptcha
            - Services_Scribd
            - Services_SharedBook
            - Services_ShortURL
            - Services_Technorati
            - Services_TinyURL
            - Services_Trackback
            - Services_Twitter
            - Services_Twitter_Uploader
            - Services_urlTea
            - Services_UseKetchup
            - Services_W3C_CSSValidator
            - Services_W3C_HTMLValidator
            - Services_Yadis
            - Services_Yahoo
            - Services_Yahoo_JP
            - Services_YouTube
            - SOAP
            - XML_RPC2
        XML:
            - XML_Feed_Parser
            - XML_FOAF
            - XML_MXML
            - XML_Parser2
            - XML_Query2XML
            - XML_Util2
            - XML_XRD
            - XML_XUL
