puphpet.vagrantfile_gce.homepage:
    pattern:  /
    defaults: { _controller: PuphpetBundle:VagrantfileGce:index }

puphpet.vagrantfile_gce.machine:
    pattern: /machine
    defaults: { _controller: PuphpetBundle:VagrantfileGce:machine }

puphpet.vagrantfile_gce.synced_folder:
    pattern: /synced-folder
    defaults: { _controller: PuphpetBundle:VagrantfileGce:syncedFolder }
