versions:
    - 'v6.2.1'
    - 'v6.2.0'
    - 'v6.1.0'
    - 'v6.0.0'
    - 'v5.9.1'
    - 'v5.9.0'
    - 'v5.8.0'
    - 'v5.7.1'
    - 'v5.7.0'
    - 'v5.6.0'
    - 'v5.5.0'
    - 'v5.4.1'
    - 'v5.4.0'
    - 'v5.3.0'
    - 'v5.2.0'
    - 'v5.11.1'
    - 'v5.11.0'
    - 'v5.10.1'
    - 'v5.10.0'
    - 'v5.1.1'
    - 'v5.1.0'
    - 'v5.0.0'
    - 'v4.4.5'
    - 'v4.4.4'
    - 'v4.4.3'
    - 'v4.4.2'
    - 'v4.4.1'
    - 'v4.4.0'
    - 'v4.3.2'
    - 'v4.3.1'
    - 'v4.3.0'
    - 'v4.2.6'
    - 'v4.2.5'
    - 'v4.2.4'
    - 'v4.2.3'
    - 'v4.2.2'
    - 'v4.2.1'
    - 'v4.2.0'
    - 'v4.1.2'
    - 'v4.1.1'
    - 'v4.1.0'
    - 'v4.0.0'
