parameters:

services:
    puphpet.extension.vagrantfile.linode.configure:
        class: Puphpet\Extension\VagrantfileLinodeBundle\Configure
        arguments:
            - "@service_container"

    puphpet.extension.vagrantfile.linode.front_controller:
        class: Puphpet\Extension\VagrantfileLinodeBundle\Controller\FrontController
        calls:
            - [ setContainer, [@service_container] ]

    puphpet.extension.vagrantfile.linode.manifest_controller:
        class: Puphpet\Extension\VagrantfileLinodeBundle\Controller\ManifestController
        calls:
            - [ setContainer, [@service_container] ]
