puphpet.php.homepage:
    pattern:  /
    defaults: { _controller: PuphpetBundle:Php:index }

puphpet.php.add_fpm_pool:
    pattern:  /add-fpm-pool
    defaults: { _controller: PuphpetBundle:Php:addFpmPool }
