puphpet.extension.vagrantfile.linode.homepage:
    pattern:  /
    defaults: { _controller: PuphpetExtensionVagrantfileLinodeBundle:Front:index }

puphpet.extension.vagrantfile.linode.synced_folder:
    pattern: /synced-folder
    defaults: { _controller: PuphpetExtensionVagrantfileLinodeBundle:Front:syncedFolder }

puphpet.extension.vagrantfile.linode.manifest:
    pattern:  /manifest
    defaults: { _controller: PuphpetExtensionVagrantfileLinodeBundle:Manifest:index }
