vm:
    box: ~
    box_url: ~
    graceful_halt_retry_count: 3
    graceful_halt_retry_interval: 1
    guest: :linux
    hostname: ~
    network:
        private_network: 192.168.56.101
        forwarded_port: []
    provider:
        virtualbox:
            name: my-vm-box
            natdnshostresolver1: on
            memory: 512
    provision:
        shell: :inline => 'if [[ ! -f /apt-get-run ]]; then sudo apt-get update && touch /apt-get-run; fi'
        puppet:
            manifests_path: manifests
            module_path: modules
            options: []
    synced_folder: []
    usable_port_range: 2200..2250
ssh:
    host: ~
    port: ~
    private_key_path: ~
    username: vagrant
    guest_port: ~
    keep_alive: true
    max_tries: 100
    timeout: 30
    forward_agent: false
    forward_x11: false
    shell: bash -l
vagrant:
    host: :detect
