vm:
    synced_folder:
        -
            source: ~/www/
            target: /var/www
            id: vagrant-root
            nfs: true
    network:
        forwarded_port:
            -
                guest: ~
                host: ~
    provision:
        puppet:
            options:
                - --verbose
