puphpet.extension.vagrantfile.homepage:
    pattern:  /
    defaults: { _controller: PuphpetExtensionVagrantfileBundle:Front:index }

puphpet.extension.vagrantfile.synced_folder:
    pattern: /synced-folder
    defaults: { _controller: PuphpetExtensionVagrantfileBundle:Front:syncedFolder }

puphpet.extension.vagrantfile.forwarded_port:
    pattern: /forwarded-port
    defaults: { _controller: PuphpetExtensionVagrantfileBundle:Front:forwardedPort }

puphpet.extension.vagrantfile.manifest:
    pattern:  /manifest
    defaults: { _controller: PuphpetExtensionVagrantfileBundle:Manifest:index }
