puphpet.extension.vagrantfile.homepage:
    pattern:  /
    defaults: { _controller: PuphpetExtensionVagrantfileBundle:Default:index }

puphpet.extension.vagrantfile.synced_folder:
    pattern: /synced-folder
    defaults: { _controller: PuphpetExtensionVagrantfileBundle:Default:syncedFolder }

puphpet.extension.vagrantfile.forwarded_port:
    pattern: /forwarded-port
    defaults: { _controller: PuphpetExtensionVagrantfileBundle:Default:forwardedPort }
