puphpet.extension.vagrantfile.homepage:
    pattern:  /
    defaults: { _controller: PuphpetExtensionVagrantfileBundle:Vagrantfile:index }

puphpet.extension.vagrantfile.synced_folder:
    pattern: /synced-folder
    defaults: { _controller: PuphpetExtensionVagrantfileBundle:Vagrantfile:syncedFolder }

puphpet.extension.vagrantfile.forwarded_port:
    pattern: /forwarded-port
    defaults: { _controller: PuphpetExtensionVagrantfileBundle:Vagrantfile:forwardedPort }
