parameters:
#    puphpet_extension_vagrantfile.example.class: Puphpet\Extension\VagrantfileBundle\Example

services:
    puphpet.extension.vagrantfile.configure:
        class: Puphpet\Extension\VagrantfileBundle\Configure
        arguments:
            - "@service_container"

    puphpet.extension.vagrantfile.main_controller:
        class: Puphpet\Extension\VagrantfileBundle\Controller\VagrantfileController
        calls:
            - [ setContainer, [@service_container] ]
