puphpet.extension.elasticsearch.homepage:
    pattern:  /
    defaults: { _controller: PuphpetExtensionElasticsearchBundle:Front:index }

puphpet.extension.php.manifest:
    pattern:  /manifest
    defaults: { _controller: PuphpetExtensionElasticsearchBundle:Manifest:index }