puphpet.firewall.homepage:
    pattern:  /
    defaults: { _controller: PuphpetBundle:Firewall:index }

puphpet.firewall.rule:
    pattern: /forwarded-port
    defaults: { _controller: PuphpetBundle:Firewall:rule }
