install: 1

settings:
    version: 56

fpm_settings:
    port: 9000

modules:
    php:
        - cli
        - intl
        - mcrypt
    pecl:
        - pecl_http

ini:
    display_errors: On
    error_reporting: -1
    session.save_path: "/var/lib/php/session"
    date.timezone: UTC

composer_home: ~
