parameters:

services:
    puphpet.extension.php.configure:
        class: Puphpet\Extension\PhpBundle\Configure
        arguments:
            - "@service_container"

    puphpet.extension.php.main_controller:
        class: Puphpet\Extension\PhpBundle\Controller\DefaultController
        calls:
            - [ setContainer, [@service_container] ]
