puphpet.vagrantfile_aws.homepage:
    pattern:  /
    defaults: { _controller: PuphpetBundle:VagrantfileAws:index }

puphpet.vagrantfile_aws.machine:
    pattern: /machine
    defaults: { _controller: PuphpetBundle:VagrantfileAws:machine }

puphpet.vagrantfile_aws.synced_folder:
    pattern: /synced-folder
    defaults: { _controller: PuphpetBundle:VagrantfileAws:syncedFolder }
