puphpet.extension.rabbitmq.homepage:
    pattern:  /
    defaults: { _controller: PuphpetExtensionRabbitMQBundle:Front:index }

puphpet.extension.rabbitmq.user:
    pattern:  /user
    defaults: { _controller: PuphpetExtensionRabbitMQBundle:Front:user }

puphpet.extension.rabbitmq.permission:
    pattern:  /permission/{userId}
    defaults: { _controller: PuphpetExtensionRabbitMQBundle:Front:permission }

puphpet.extension.rabbitmq.manifest:
    pattern:  /manifest
    defaults: { _controller: PuphpetExtensionRabbitMQBundle:Manifest:index }
