puphpet.main:
    resource: "@PuphpetMainBundle/Resources/config/routing.yml"
    prefix:   /

puphpet.extension.vagrantfile:
    resource: "@PuphpetExtensionVagrantfileBundle/Resources/config/routing.yml"
    prefix:   /extension/vagrantfile

puphpet.extension.server_basics:
    resource: "@PuphpetExtensionServerBasicsBundle/Resources/config/routing.yml"
    prefix:   /extension/server-basics

puphpet.extension.apache:
    resource: "@PuphpetExtensionApacheBundle/Resources/config/routing.yml"
    prefix:   /extensions/apache

puphpet.extension.php:
    resource: "@PuphpetExtensionPhpBundle/Resources/config/routing.yml"
    prefix:   /extensions/php

puphpet.extension.xdebug:
    resource: "@PuphpetExtensionXdebugBundle/Resources/config/routing.yml"
    prefix:   /extensions/xdebug

puphpet.extension.mysql:
    resource: "@PuphpetExtensionMysqlBundle/Resources/config/routing.yml"
    prefix:   /extensions/mysql

puphpet.extension.postgresql:
    resource: "@PuphpetExtensionPostgresqlBundle/Resources/config/routing.yml"
    prefix:   /extensions/postgresql
