parameters:

services:
    puphpet.extension.vagrantfile.ikoulacloud.configure:
        class: Puphpet\Extension\VagrantfileIkoulaCloudBundle\Configure
        arguments:
            - @service_container

    puphpet.extension.vagrantfile.ikoulacloud.front_controller:
        class: Puphpet\Extension\VagrantfileIkoulaCloudBundle\Controller\FrontController
        calls:
            - [ setContainer, [@service_container] ]

    puphpet.extension.vagrantfile.ikoulacloud.manifest_controller:
        class: Puphpet\Extension\VagrantfileIkoulaCloudBundle\Controller\ManifestController
        calls:
            - [ setContainer, [@service_container] ]
