vm:
    box: digital_ocean
    graceful_halt_retry_count: 3
    graceful_halt_retry_interval: 1
    guest: :linux
    hostname: master
    network:
        private_network: 192.168.56.101
        forwarded_port: []
    provider:
        digital_ocean:
            image: ~
            region: ~
            size: ~
            client_id: ~
            api_key: ~
    provision:
        shell: ':inline => "if [[ ! -f /apt-get-run ]]; then sudo apt-get update && sudo apt-get install -y puppet && touch /apt-get-run; fi"'
        puppet:
            manifests_path: manifests
            module_path: modules
            options:
                - "--verbose"
    synced_folder: []
    usable_port_range: 2200..2250

ssh:
    host: ~
    port: ~
    private_key_path: ~
    username: vagrant
    guest_port: ~
    keep_alive: true
    max_tries: 100
    timeout: 30
    forward_agent: false
    forward_x11: false
    shell: bash -l

vagrant:
    host: :detect

empty_synced_folder:
    source: ~
    target: ~
    id: ~
    nfs: true

available_images:
    -
        image: Debian 7.0 x64
        long_name: Debian Wheezy 7.0 x64
        php_versions:
            - 5.5
            - 5.4
    -
        image: Debian 6.0 x64
        long_name: Debian Squeeze 6.0 x64
        php_versions:
            - 5.5
            - 5.4
    -
        image: Ubuntu 13.04 x64
        long_name: Ubuntu Raring 13.04 x64
        php_versions:
            - 5.5
            - 5.4
    -
        image: Ubuntu 12.10 x64
        long_name: Ubuntu Quantal 12.10 x64
        php_versions:
            - 5.5
            - 5.4
    -
        image: Ubuntu 12.04 x64
        long_name: Ubuntu Precise 12.04 x64
        php_versions:
            - 5.5
            - 5.4
            - 5.3

available_sizes:
    512MB: 512MB / 1 CPU / 20GB SSD DISK / 1TB TRANSFER
    1GB: 1GB / 1 CPU / 30GB SSD DISK / 2TB TRANSFER
    2GB: 2GB / 2 CPUS / 40GB SSD DISK / 3TB TRANSFER
    4GB: 4GB / 2 CPUS / 60GB SSD DISK / 4TB TRANSFER
    8GB: 8GB / 4 CPUS / 80GB SSD DISK / 5TB TRANSFER
    16GB: 16GB / 8 CPUS / 160GB SSD DISK / 6TB TRANSFER
    32GB: 32GB / 12 CPUS / 320GB SSD DISK / 7TB TRANSFER
    48GB: 48GB / 16 CPUS / 480GB SSD DISK / 8TB TRANSFER
    64GB: 64GB / 20 CPUS / 640GB SSD DISK / 9TB TRANSFER
    96GB: 96GB / 24 CPUS / 960GB SSD DISK / 10TB TRANSFER

available_regions:
    - New York 1
    - New York 2
    - San Francisco 1
    - Amsterdam 1
