puphpet.extension.vagrantfile_digitalocean.homepage:
    pattern:  /
    defaults: { _controller: PuphpetExtensionVagrantfileDigitalOceanBundle:Front:index }

puphpet.extension.vagrantfile_digitalocean.synced_folder:
    pattern: /synced-folder
    defaults: { _controller: PuphpetExtensionVagrantfileDigitalOceanBundle:Front:syncedFolder }
