install: 1

settings:
    override_options: {}

databases:
    -
        name: dbname
        user: dbuser
        password: 123
        host: localhost
        grant:
            - ALL
        sql_file: ~
