parameters:

services:
    puphpet.extension.mysql.configure:
        class: Puphpet\Extension\MysqlBundle\Configure
        arguments:
            - "@service_container"

    puphpet.extension.mysql.main_controller:
        class: Puphpet\Extension\MysqlBundle\Controller\MysqlController
        calls:
            - [ setContainer, [@service_container] ]
