parameters:

services:
    puphpet.extension.server_basics.configure:
        class: Puphpet\Extension\ServerBasicsBundle\Configure
        arguments:
            - "@service_container"

    puphpet.extension.server_basics.front_controller:
        class: Puphpet\Extension\ServerBasicsBundle\Controller\FrontController
        calls:
            - [ setContainer, [@service_container] ]
