parameters:

services:
    puphpet.extension.server_basics.configure:
        class: Puphpet\Extension\ServerBasicsBundle\Configure
        arguments:
            - "@service_container"

    puphpet.extension.server_basics.main_controller:
        class: Puphpet\Extension\ServerBasicsBundle\Controller\ServerBasicsController
        calls:
            - [ setContainer, [@service_container] ]
