vhosts:
    -
        servername: awesome.dev
        serveraliases:
            - www.awesome.dev
        docroot: /var/www/awesome.dev
        port: 80
        envvars:
            - APP_ENV dev
        index_files:
            - index.html
            - index.htm
            - index.php
