puphpet.extension.nginx.homepage:
    pattern:  /
    defaults: { _controller: PuphpetExtensionNginxBundle:Front:index }

puphpet.extension.nginx.vhost:
    pattern:  /vhost
    defaults: { _controller: PuphpetExtensionNginxBundle:Front:vhost }
