puphpet.extension.python.homepage:
    path:     /
    defaults: { _controller: PuphpetExtensionPythonBundle:Front:index }

puphpet.extension.python.add_version:
    pattern:  /add-version
    defaults: { _controller: PuphpetExtensionPythonBundle:Front:addVersion }

puphpet.extension.python.manifest:
    pattern:  /manifest
    defaults: { _controller: PuphpetExtensionPythonBundle:Manifest:index }
