# name of default editions
edition_default: default

# configuration of all available editions
editions:
  default:
    php:
      modules:
        - 'php5-cli'
        - 'php5-curl'
        - 'php5-intl'
        - 'php5-mcrypt'
      inilist:
        php:
          date.timezone: 'America/Chicago'
        custom:
          display_errors: 'On'
          error_reporting: '-1'
  symfony:
    builder: plugin.symfony.configuration_builder
    template: '@Symfony/start.html.twig'
    vagrant:
      boxes:
        lucid32:   {url: "http://files.vagrantup.com/lucid32.box", name: "Ubuntu Lucid 32 Bit (10.04.4 LTS)"}
        lucid64:   {url: "http://files.vagrantup.com/lucid64.box", name: "Ubuntu Lucid 64 Bit (10.04.4 LTS)"}
        precise32: {url: "http://files.vagrantup.com/precise32.box", name: "Ubuntu Precise 32 Bit (12.04.2 LTS)"}
        precise64: {url: "http://files.vagrantup.com/precise64.box", name: "Ubuntu Precise 64 Bit (12.04.2 LTS)"}
      default_box: precise64
    php:
      version: php54
      modules:
        composer:
          installed: true
        pear:
          installed: false
        php:
          - 'php5-cli'
          - 'php5-curl'
          - 'php5-intl'
          - 'php5-mcrypt'
          - 'php-apc'
          - 'php5-gd'
          - 'php5-intl'
          - 'php5-sqlite'
        xdebug:
          installed: true
          remote_autostart: false
          remote_port: 9000
      inilist:
        php:
          date.timezone: 'America/Chicago'
        symfony:
          display_errors:            'On'
          error_reporting:           '-1'
          'xdebug.max_nesting_level': 250

  puphpet:
    builder: plugin.puphpet.configuration_builder
    template: '@Puphpet/start.html.twig'
    box:
      name: precise64
      url:  'http://files.vagrantup.com/precise64.box'
      ip:   '192.168.56.101'
      memory: 1024
      port_forward: {host: false, guest: false}

    server:
      packages:
        - 'python-software-properties'
        - 'puppet-lint'
        - 'vim'
        - 'curl'
        - 'zip'
        - 'rsync'
    php:
      version: php54
      modules:
        composer:
          installed: true
        pear:
          installed: false
        php:
          - 'php5-cli'
          - 'php5-curl'
          - 'php5-intl'
          - 'php5-mcrypt'
        xdebug:
          installed: true
          remote_autostart: false
          remote_port: 9000
      inilist:
        puphpet:
          date.timezone: 'America/Chicago'
          display_errors:            'On'
          error_reporting:           '-1'
