available_privileges:
    "Give all":
        - ALL
    "or, Give some":
        - SELECT
        - INSERT
        - UPDATE
        - DELETE
        - TRUNCATE
        - REFERENCE
        - TRIGGER
        - CREATE
        - CONNECT
        - TEMPORARY
        - EXECUTE
        - USAGE

empty_database:
    privileges: []
    username: ~
    password: ~
    db_name: ~
    sql_file: ~
