puphpet.extension.postgresql.homepage:
    pattern:  /
    defaults: { _controller: PuphpetExtensionPostgresqlBundle:Postgresql:index }

puphpet.extension.postgresql.add_database:
    pattern:  /add-database
    defaults: { _controller: PuphpetExtensionPostgresqlBundle:Postgresql:addDatabase }
