parameters:

services:
    puphpet.extension.postgresql.configure:
        class: Puphpet\Extension\PostgresqlBundle\Configure
        arguments:
            - "@service_container"

    puphpet.extension.postgresql.main_controller:
        class: Puphpet\Extension\PostgresqlBundle\Controller\PostgresqlController
        calls:
            - [ setContainer, [@service_container] ]
