modules: []
vhosts: []

user: 'www-data'
group: 'www-data'
default_vhost: false
mpm_module: prefork

empty_vhost:
    servername: ~
    serveraliases: []
    docroot: ~
    port: 80
    setenv: []

available_modules:
    - rewrite
    - actions
    - asis
    - auth_digest
    - authn_alias
    - authn_anon
    - authn_dbd
    - authn_dbm
    - authn_default
    - authnz_ldap
    - authz_dbm
    - authz_owner
    - cache
    - cern_meta
    - cgid
    - charset_lite
    - dav_fs
    - dav
    - dav_lock
    - dbd
    - disk_cache
    - dump_io
    - expires
    - ext_filter
    - file_cache
    - filter
    - headers
    - ident
    - imagemap
    - include
    - info
    - ldap
    - log_forensic
    - mem_cache
    - mime_magic
    - proxy_ajp
    - proxy_balancer
    - proxy_connect
    - proxy_ftp
    - proxy_http
    - proxy
    - proxy_scgi
    - speling
    - ssl
    - substitute
    - suexec
    - unique_id
    - userdir
    - usertrack
    - version
    - vhost_alias
