modules:
    - rewrite

vhosts:
    -
        servername: awesome.dev
        serveraliases:
            - www.awesome.dev
        docroot: /var/www/awesome
        port: 80
        envvars:
            - APP_ENV dev

empty_vhost:
    servername: ~
    serveraliases: []
    docroot: ~
    port: 80
    envvars: []
