puphpet.extension.apache.homepage:
    pattern:  /
    defaults: { _controller: PuphpetExtensionApacheBundle:Apache:index }

puphpet.extension.apache.vhost:
    pattern:  /vhost
    defaults: { _controller: PuphpetExtensionApacheBundle:Apache:vhost }
