parameters:

services:
    puphpet.extension.ruby.configure:
        class: Puphpet\Extension\RubyBundle\Configure
        arguments:
            - "@service_container"

    puphpet.extension.ruby.front_controller:
        class: Puphpet\Extension\RubyBundle\Controller\FrontController
        calls:
            - [ setContainer, [@service_container] ]

    puphpet.extension.ruby.manifest_controller:
        class: Puphpet\Extension\RubyBundle\Controller\ManifestController
        calls:
            - [ setContainer, [@service_container] ]
