puphpet.vagrantfile_local.homepage:
    pattern:  /
    defaults: { _controller: PuphpetBundle:VagrantfileLocal:index }

puphpet.vagrantfile_local.machine:
    pattern: /machine
    defaults: { _controller: PuphpetBundle:VagrantfileLocal:machine }

puphpet.vagrantfile_local.machine_forwarded_port:
    pattern: /machine-forwarded-port/{mId}
    defaults: { _controller: PuphpetBundle:VagrantfileLocal:machineForwardedPort }

puphpet.vagrantfile_local.synced_folder:
    pattern: /synced-folder
    defaults: { _controller: PuphpetBundle:VagrantfileLocal:syncedFolder }
