puphpet.main.homepage:
    pattern:  /
    defaults: { _controller: PuphpetMainBundle:Front:index }

puphpet.main.upload_config:
    pattern:  /upload-config
    defaults: { _controller: PuphpetMainBundle:Front:uploadConfig }

puphpet.main.generate_archive:
    pattern:  /generate-archive
    defaults: { _controller: PuphpetMainBundle:Front:generateArchive }

puphpet.main.about:
    pattern:  /about
    defaults: { _controller: PuphpetMainBundle:Front:about }

puphpet.main.help:
    pattern:  /help
    defaults: { _controller: PuphpetMainBundle:Front:help }

puphpet.main.github_btn:
    pattern:  /github-btn
    defaults: { _controller: PuphpetMainBundle:Front:githubBtn }
