puphpet_main_homepage:
    pattern:  /
    defaults: { _controller: PuphpetMainBundle:Default:index }

puphpet_main_plugin_vagrantfile_synced_folder:
    pattern: /plugin/vagrantfile/synced_folder
    defaults: { _controller: PuphpetMainBundle:Plugin/Vagrantfile:syncedFolder}

puphpet_main_plugin_vagrantfile_forwarded_port:
    pattern: /plugin/vagrantfile/forwarded_port
    defaults: { _controller: PuphpetMainBundle:Plugin/Vagrantfile:forwardedPort}
