services:
    randomlib:
        class: RandomLib\Factory

    puphpet.extension.manager:
        class: Puphpet\MainBundle\Extension\Manager
        arguments:
            - @service_container
        calls:
        # deploy target
            - [ addExtension, [ 'vagrantfile-local' ] ]
            - [ addExtension, [ 'vagrantfile-rackspace' ] ]
            - [ addExtension, [ 'vagrantfile-linode' ] ]
            - [ addExtension, [ 'vagrantfile-softlayer' ] ]
            - [ addExtension, [ 'vagrantfile-aws' ] ]
            - [ addExtension, [ 'vagrantfile-gce' ] ]
            - [ addExtension, [ 'vagrantfile-digitalocean' ] ]
            - [ addExtension, [ 'vagrantfile-ikoulacloud' ] ]
        # system
            - [ addExtension, [ 'package' ] ]
            - [ addExtension, [ 'user-group' ] ]
            - [ addExtension, [ 'firewall' ] ]
            - [ addExtension, [ 'cron-job' ] ]
        # web server
            - [ addExtension, [ 'nginx' ] ]
            - [ addExtension, [ 'apache' ] ]
        # language
            - [ addExtension, [ 'php' ] ]
            - [ addExtension, [ 'xdebug' ] ]
            - [ addExtension, [ 'xhprof' ] ]
            - [ addExtension, [ 'wpcli' ] ]
            - [ addExtension, [ 'drush' ] ]
            - [ addExtension, [ 'ruby' ] ]
            - [ addExtension, [ 'python' ] ]
            - [ addExtension, [ 'nodejs' ] ]
            - [ addExtension, [ 'hhvm' ] ]
        # database
            - [ addExtension, [ 'mysql' ] ]
            - [ addExtension, [ 'postgresql' ] ]
            - [ addExtension, [ 'mongodb' ] ]
            - [ addExtension, [ 'redis' ] ]
            - [ addExtension, [ 'sqlite' ] ]
        # mail
            - [ addExtension, [ 'mailcatcher' ] ]
        # work queue
            - [ addExtension, [ 'beanstalkd' ] ]
            - [ addExtension, [ 'rabbitmq' ] ]
        # search server
            - [ addExtension, [ 'elastic-search' ] ]
            - [ addExtension, [ 'solr' ] ]

    puphpet.twig.base_extension:
        class: Puphpet\MainBundle\Twig\BaseExtension
        arguments:
            - @randomlib
        tags:
            - { name: twig.extension }
