parameters:
#    puphpet_main.example.class: Puphpet\MainBundle\Example

services:
    randomlib:
        class: RandomLib\Factory

    puphpet.twig.base_extension:
        class: Puphpet\MainBundle\Twig\BaseExtension
        arguments:
            - "@randomlib"
        tags:
            - { name: twig.extension }
