imports:
    - { resource: vagrantfile-local/services.yml }

services:
    randomlib:
        class: RandomLib\Factory

    puphpet.extension.manager:
        class: Puphpet\MainBundle\Extension\Manager
        arguments:
            - @service_container
        calls:
        # deploy target
            - [ addExtension, [ 'vagrantfile-local' ] ]
            - [ addExtension, [ 'vagrantfile-rackspace' ] ]
            - [ addExtension, [ 'vagrantfile-linode' ] ]
            - [ addExtension, [ 'vagrantfile-softlayer' ] ]
            - [ addExtension, [ 'vagrantfile-aws' ] ]
            - [ addExtension, [ 'vagrantfile-gce' ] ]
            - [ addExtension, [ 'vagrantfile-digitalocean' ] ]
            - [ addExtension, [ 'vagrantfile-ikoulacloud' ] ]
        # system
            - [ addExtension, [ 'package' ] ]
            - [ addExtension, [ 'user-group' ] ]
            - [ addExtension, [ 'firewall' ] ]
            - [ addExtension, [ 'cron-job' ] ]
        # web server
            - [ addExtension, [ 'nginx' ] ]
            - [ addExtension, [ 'apache' ] ]

    puphpet.twig.base_extension:
        class: Puphpet\MainBundle\Twig\BaseExtension
        arguments:
            - @randomlib
        tags:
            - { name: twig.extension }
