parameters:
#    puphpet_main.example.class: Puphpet\MainBundle\Example

services:
    randomlib:
        class: RandomLib\Factory

    puphpet.extension.manager:
        class: Puphpet\MainBundle\Extension\Manager
        arguments:
            - "@service_container"
        calls:
            - [ addExtension, [ @puphpet.extension.vagrantfile.configure ] ]
            - [ addExtension, [ @puphpet.extension.server_basics.configure ] ]
            - [ addExtension, [ @puphpet.extension.apache.configure ] ]
            - [ addExtension, [ @puphpet.extension.php.configure ] ]
            - [ addExtension, [ @puphpet.extension.xdebug.configure ] ]
        # database group
            - [ addExtensionToGroup, [ 'database', @puphpet.extension.mysql.configure ] ]
            - [ addExtensionToGroup, [ 'database', @puphpet.extension.postgresql.configure ] ]

    puphpet.twig.base_extension:
        class: Puphpet\MainBundle\Twig\BaseExtension
        arguments:
            - "@randomlib"
        tags:
            - { name: twig.extension }
