empty_synced_folder:
    source: ~
    target: ~
    id: vagrant-root
    nfs: 'false'

available_boxes:
    -
        url: http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210.box
        os: centos
        short_name: centos64
        long_name: CentOS 6.4 x64
        php_versions:
            - 5.5
            - 5.4
    -
        url: https://puphpet.s3.amazonaws.com/centos64-x64-vbox43.box
        os: centos
        short_name: centos64-x64-vbox43
        long_name: CentOS 6.4 x64 - VirtualBox 4.3+
        php_versions:
            - 5.5
            - 5.4
    -
        url: http://puppet-vagrant-boxes.puppetlabs.com/debian-70rc1-x64-vbox4210.box
        os: debian
        short_name: wheezy64
        long_name: Debian Wheezy 7.0rc1 x64
        php_versions:
            - 5.5
            - 5.4
    -
        url: http://puppet-vagrant-boxes.puppetlabs.com/debian-607-x64-vbox4210.box
        os: debian
        short_name: squeeze64
        long_name: Debian Squeeze 6.0.7 x64
        php_versions:
            - 5.4
            - 5.3
    -
        url: http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210.box
        os: ubuntu
        short_name: precise64
        long_name: Ubuntu Precise 12.04 x64
        php_versions:
            - 5.4
            - 5.3
    -
        url: http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-10044-x64-vbox4210.box
        os: ubuntu
        short_name: lucid64
        long_name: Ubuntu Lucid 10.04 x64
        php_versions:
            - 5.4
            - 5.3
