vm:
    box: wheezy64
    box_url: http://puppet-vagrant-boxes.puppetlabs.com/debian-70rc1-x64-vbox4210.box
    hostname: ~
    network:
        private_network: 192.168.56.101
        forwarded_port: []
    provider:
        virtualbox:
            modifyvm:
                name: my-vm-box
                natdnshostresolver1: on
                memory: 512
            setextradata:
                "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root": 1
    provision:
        "shell, :path": "shell/librarian-puppet-vagrant.sh"
        "shell, :inline": "if [[ ! -f /apt-get-run ]]; then sudo apt-get update && touch /apt-get-run; fi"
        puppet:
            manifests_path: "puppet/manifests"
            module_path: "puppet/modules"
            options:
                - "--verbose"
                - "--hiera_config /vagrant/hiera.yaml"
                - "--parser=future"
    synced_folder: []
    usable_port_range: 2200..2250

ssh:
    host: ~
    port: ~
    private_key_path: ~
    username: vagrant
    guest_port: ~
    keep_alive: true
    forward_agent: false
    forward_x11: false
    shell: bash -l

vagrant:
    host: :detect
