vm:
    box: wheezy64
    box_url: http://puppet-vagrant-boxes.puppetlabs.com/debian-70rc1-x64-vbox4210.box
    graceful_halt_retry_count: 3
    graceful_halt_retry_interval: 1
    guest: :linux
    hostname: ~
    network:
        private_network: 192.168.56.101
        forwarded_port: []
    provider:
        virtualbox:
            modifyvm:
                name: my-vm-box
                natdnshostresolver1: on
                memory: 512
            setextradata:
                "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root": 1
    provision:
        shell: ':inline => "if [[ ! -f /apt-get-run ]]; then sudo apt-get update && touch /apt-get-run; fi"'
        puppet:
            manifests_path: manifests
            module_path: modules
            options:
                - "--verbose"
    synced_folder: []
    usable_port_range: 2200..2250

ssh:
    host: ~
    port: ~
    private_key_path: ~
    username: vagrant
    guest_port: ~
    keep_alive: true
    max_tries: 100
    timeout: 30
    forward_agent: false
    forward_x11: false
    shell: bash -l

vagrant:
    host: :detect

empty_synced_folder:
    source: ~
    target: ~
    id: ~
    nfs: true

available_boxes:
    -
        url: http://puppet-vagrant-boxes.puppetlabs.com/debian-70rc1-x64-vbox4210.box
        os: debian
        short_name: wheezy64
        long_name: Debian Wheezy 7.0rc1 x64
        php_versions:
            - 5.5
            - 5.4
    -
        url: http://puppet-vagrant-boxes.puppetlabs.com/debian-607-x64-vbox4210.box
        os: debian
        short_name: squeeze64
        long_name: Debian Squeeze 6.0.7 x64
        php_versions:
            - 5.4
            - 5.3
    -
        url: http://files.vagrantup.com/precise64.box
        os: ubuntu
        short_name: precise64
        long_name: Ubuntu Precise 12.04 x64
        php_versions:
            - 5.5
            - 5.4
            - 5.3
    -
        url: http://files.vagrantup.com/lucid64.box
        os: ubuntu
        short_name: lucid64
        long_name: Ubuntu Lucid 10.04 x64
        php_versions:
            - 5.5
            - 5.4
            - 5.3
