vm:
    provider:
        virtualbox: []
    synced_folder:
        -
            source: ~/www/
            target: /var/www
            id: webroot
            nfs: true
    network:
        forwarded_port:
            -
                guest: ~
                host: ~
    provision:
        puppet:
            options:
                - "--verbose"
ssh:
    forward_agent: true
