vm:
    provider:
        virtualbox: []
    synced_folder:
        -
            source: ./
            target: /var/www
            id: webroot
            nfs: true
    network:
        forwarded_port:
            -
                guest: ~
                host: ~
    provision:
        puppet:
            options:
                - "--verbose"
                - "--hiera_config /vagrant/hiera.yaml"
                - "--parser future"
ssh:
    forward_agent: true
