parameters:

services:
    puphpet.extension.vagrantfilelocal.configure:
        class: Puphpet\Extension\VagrantfileLocalBundle\Configure
        arguments:
            - "@service_container"

    puphpet.extension.vagrantfilelocal.front_controller:
        class: Puphpet\Extension\VagrantfileLocalBundle\Controller\FrontController
        calls:
            - [ setContainer, [@service_container] ]

    puphpet.extension.vagrantfilelocal.manifest_controller:
        class: Puphpet\Extension\VagrantfileLocalBundle\Controller\ManifestController
        calls:
            - [ setContainer, [@service_container] ]
